version: '3.8'

services:
  app:
    build: .docker
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - upload_laravel_docker
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    networks:
      - upload_laravel_docker
    ports:
      - 80:80
    depends_on:
      - app
  mysql:
    image: mysql:5.7
    networks:
      - upload_laravel_docker
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysqltesting
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--max_allowed_packet=32505856','--sql_mode=']

networks:
  upload_laravel_docker: